game:
  display:
    height: 720
    width: 1280
  max_fps: 240
  name: RythmoSphere
  version: 0.1.3-SNAPSHOT
options:
  display_height_options:
  - 600
  - 720
  - 1080
  - 1440
  display_width_options:
  - 800
  - 1280
  - 1920
  - 2560
  max_fps_options:
  - 30
  - 60
  - 120
  - 240
